//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonSubjects
    {
        public int subjectID { get; set; }
        public int lessonID { get; set; }
        public string subject { get; set; }
    
        public virtual Lessons Lessons { get; set; }
    }
}
