//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Class
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EClassEntities : DbContext
    {
        public EClassEntities()
            : base("name=EClassEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Choices> Choices { get; set; }
        public virtual DbSet<Lessons> Lessons { get; set; }
        public virtual DbSet<LessonSubjects> LessonSubjects { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Schools> Schools { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<TestQuestions> TestQuestions { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
        public virtual DbSet<QuestionChoices> QuestionChoices { get; set; }
    }
}
