//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int teacherID { get; set; }
        public string fullName { get; set; }
        public int schoolID { get; set; }
        public int branchID { get; set; }
    
        public virtual Lessons Lessons { get; set; }
        public virtual Schools Schools { get; set; }
    }
}
