//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestions
    {
        public int testID { get; set; }
        public int questionID { get; set; }
        public Nullable<bool> isTrue { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
